### ISSUE TITLE
Open all tabs in a private window

### ISSUE THREAD

**Issue by dardoor** [allen505/save-for-later-firefox#2]
It seems there's no way to open all the saved tabs at once (the whole session) in a private window. Even if you're already in a private window, they open in a regular window.

You can only open them individually, if you're already in a private window, by L-clicking (middle click doesn't work).
That's better than nothing, but I wish you could open them all at once.

**Comment by allen505** [comment]
This is a good idea. The save opened should reflect the type of window (normal/private) that it is opened in.
To check whether the extension is in a private window [inIncognitoContext](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/inIncognitoContext) could be used, (research required)
To open the tabs in a private window, [windows.create](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create) can be used with the `incognito` flag set to true.

**Comment by Abbaskt** [comment]
[inIncognitoContext](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/inIncognitoContext) cannot be used as it will not recognize a private window until `"incognito": "split"` is mentioned in the Manifest files as stated [here](https://developer.chrome.com/docs/extensions/reference/extension/#property-inIncognitoContext).
Instead an example mentioned [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) can be used to derive if the last tab was a private tab or not.

**Comment by allen505** [comment]
Sure, makes sense

**Comment by allen505** [comment]
Closing this issue as the PR is merged. Thanks @Abbaskt
